### ISSUE TITLE
Error al vaciar la baraja

### ISSUE THREAD

**Issue by enmabry** [mmasias/23-24-pyKlondike#1]
![Captura de pantalla 2024-05-07 143354](https://github.com/mmasias/23-24-pyKlondike/assets/144849127/18e4d975-1027-4bdb-905f-124c8ce6b7c0)

**Comment by mmasias** [comment]
Detectado el error: [no he verificado si la baraja está vacía antes de imprimirla](https://github.com/mmasias/23-24-pyKlondike/blob/e1a236e355c8e7401fc25f2d6823600b88d4c2d6/src/Baraja.java#L40)!

![image](https://github.com/mmasias/23-24-pyKlondike/assets/8528047/e6025206-7e95-4e50-8b16-9a4364bd5901)

Lo corrijo y lo dejo subido. Thanks @enmabry!!!

**Comment by mmasias** [comment]
Listo: corregido y arriba.

![image](https://github.com/mmasias/23-24-pyKlondike/assets/8528047/284c88fa-76cc-437f-bd65-5206c98f7905)
